name: Refdoc generate markdown file
description: |
  This make markdown file for displaying informative articles.
inputs:
  refdoc: 
    required: true
    description: The filepath of config file (it must be yaml file).
  markdown: 
    required: false
    default: refdoc/README.md
    description: The filepath of generated markdown file.
  iscache:
    required: false
    default: true
    description: |
      Create cache file or not.
      Cache file containing cached title and foundAt data.
  cachepath:
    required: false
    default: refdoc/cache.json
    description: The filepath of cached json file
runs:
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ^1.18
        check-latest: true
        cache: true
    - run: go run .
