name: Check it
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  REPO_NAME: streamwest-1629/refdoc
  BRANCH_TAG: latest
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to the Container Registry (Github Packages)
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set metadata for Docker Image
      id: metadata
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}
        flavor: |
          latest=true
          prefix=devcontainer-,onlatest=true
        tags: |
          type=sha,format=long
          type=raw,value=${{ env.BRANCH_TAG }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        push: true
        context: .
        file: .devcontainer/Dockerfile
        platforms: linux/amd64
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_NAME }}:buildcache
        cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_NAME }}:buildcache,mode=max

  check_it:
    name: Check it
    runs-on: ubuntu-22.04
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Run
        uses: ./.
        with:
          refdoc: refdoc.yaml
      - name: Cat refdoc.md
        run: cat ./refdoc/README.md
      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Commit and Push
        if: ${{ github.event_name == 'push' }}
        uses: actions-js/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "[BOT] update at ${{ env.CURRENT_DATETIME }}"
          branch: ${{ github.ref_name }}
    